#!/usr/bin/env python

"""
Collection of tools for circuit building.
"""

from builtins import input  # pylint: disable=redefined-builtin

import logging
import shutil

import click
import numpy as np
import pandas as pd

from voxcell import CellCollection, VoxelData
from brainbuilder.utils import bbp


@click.group()
def app():
    """ Collection of tools for circuit building """
    pass


@app.group(name="mvd3")
def _mvd3():
    """ Tools for working with MVD3 """
    pass


@_mvd3.command()
@click.argument("mvd3")
@click.option("-p", "--prop", help="Property name to use", required=True)
@click.option("-d", "--voxel-data", help="Path NRRD with to volumetric data", required=True)
@click.option("-o", "--output", help="Path to output MVD3", required=True)
def add_property(mvd3, prop, voxel_data, output):
    """ Add property to MVD3 based on volumetric data """
    cells = CellCollection.load(mvd3)
    if prop in cells.properties:
        choice = input(
            "There is already '%s' property in the provided MVD3. Overwrite (y/n)? " % prop
        )
        if choice.lower() not in ('y', 'yes'):
            return
    voxel_data = VoxelData.load_nrrd(voxel_data)
    cells.properties[prop] = voxel_data.lookup(cells.positions)
    cells.save(output)


@_mvd3.command()
@click.argument("mvd3")
@click.option("--recipe", help="Path to builder recipe XML", required=True)
@click.option("-o", "--output", help="Path to output MVD3", required=True)
def reorder_mtypes(mvd3, recipe, output):
    """ Align /library/mtypes with builder recipe """
    tmp_path = output + "~"
    shutil.copy(mvd3, tmp_path)
    bbp.reorder_mtypes(tmp_path, recipe)
    shutil.move(tmp_path, output)


@_mvd3.command()
@click.argument("mvd3")
@click.option("--morphdb", help="Path to extNeuronDB.dat", required=True)
@click.option("--seed", type=int, help="Pseudo-random generator seed", default=0)
@click.option("-o", "--output", help="Path to output MVD3", required=True)
def assign_emodels(mvd3, morphdb, seed, output):
    """ Assign /cells/properties/me_combo """
    np.random.seed(seed)

    mvd3 = CellCollection.load(mvd3)
    morphdb = bbp.load_neurondb_v3(morphdb)

    result = bbp.assign_emodels(mvd3, morphdb)
    result.save(output)


@_mvd3.command()
@click.argument("mvd3")
@click.option("--seeds", help="Comma-separated circuit seeds (4 floats)", required=True)
@click.option("-o", "--output", help="Path to output MVD3", required=True)
def assign_seeds(mvd3, seeds, output):
    """ Assign /circuit/seeds """
    seeds = [float(x) for x in seeds.split(",")]
    assert len(seeds) == 4
    mvd3 = CellCollection.load(mvd3)
    mvd3.seeds = np.array(seeds, dtype=np.float64)
    mvd3.save(output)


@_mvd3.command()
@click.argument("mvd3")
@click.option("--morph-dir", help="Path to morphology folder", required=True)
@click.option("-o", "--output", help="Path to output MVD2", required=True)
def to_mvd2(mvd3, morph_dir, output):
    """ Convert to MVD2 """
    cells = CellCollection.load(mvd3)
    bbp.save_mvd2(output, morph_dir, cells)


@_mvd3.command()
@click.argument("mvd3", nargs=-1)
@click.option("-o", "--output", help="Path to output MVD3", required=True)
def merge(mvd3, output):
    """ Merge multiple MVD3 files """
    chunks = [CellCollection.load(filepath).as_dataframe() for filepath in mvd3]
    merged = pd.concat(chunks, ignore_index=True)
    merged.index = 1 + np.arange(len(merged))
    CellCollection.from_dataframe(merged).save(output)


@app.group(name="targets")
def _targets():
    """ Tools for working with .target files """
    pass


@_targets.command()
@click.argument("mvd3")
@click.option("--etype", is_flag=True, help="Include etype-based targets")
@click.option("--region", is_flag=True, help="Include region-based targets")
@click.option("--layer", is_flag=True, help="Include layer-based targets (SSCX)")
@click.option("--column", is_flag=True, help="Include column-based targets (SSCX)")
@click.option("-o", "--output", help="Path to output .target file", required=True)
def from_mvd3(mvd3, etype, region, layer, column, output):
    """ Generate .target file from MVD3 """
    cells = CellCollection.load(mvd3).as_dataframe()
    SYNAPSE_CLASSES = {
        'EXC': 'Excitatory',
        'INH': 'Inhibitory',
    }
    with open(output, 'w') as f:
        bbp.write_target(f, 'Mosaic', include_targets=['All'])
        bbp.write_target(f, 'All', include_targets=sorted(cells['mtype'].unique()))
        bbp.write_property_targets(f, cells, 'synapse_class', mapping=SYNAPSE_CLASSES.__getitem__)
        bbp.write_property_targets(f, cells, 'mtype')
        if etype:
            bbp.write_property_targets(f, cells, 'etype')
        if region:
            bbp.write_property_targets(f, cells, 'region')
        if layer:
            bbp.write_property_targets(f, cells, 'layer', mapping=lambda x: "Layer%d" % x)
        if column:
            bbp.write_property_targets(f, cells, 'hypercolumn', mapping=lambda x: "mc%d_Column" % x)


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    app()
