#!/usr/bin/env python

""" Generate start.ncs from MVD3. """

import argparse

from voxcell.core import CellCollection


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Generate start.ncs contents from MVD3 file")
    parser.add_argument(
        dest="input",
        help="Path to input .mvd3 file"
    )
    parser.add_argument(
        dest="output",
        help="Path to output .ncs file"
    )
    args = parser.parse_args()

    cells = CellCollection.load(args.input).as_dataframe()

    with open(args.output, 'w') as f:
        f.write("Cells {num}\n".format(num=len(cells)))
        f.write("{\n")
        for gid, row in cells.iterrows():
            f.write("  a{gid} 0 0 0 {me_combo}\n".format(gid=gid, me_combo=row['me_combo']))
        f.write("}\n")
