#!/usr/bin/env python

import argparse
import numpy as np
import pandas as pd

from voxcell import CellCollection


def run(filepaths, output_path):
    chunks = [CellCollection.load(filepath).as_dataframe() for filepath in filepaths]
    merged = pd.concat(chunks, ignore_index=True)
    merged.index = 1 + np.arange(len(merged))
    CellCollection.from_dataframe(merged).save(output_path)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Merge several MVD3 files")
    parser.add_argument(
        '-i', '--input',
        type=str,
        nargs='+',
        required=True,
        help="Input file paths"
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        required=True,
        help="Output file path"
    )
    args = parser.parse_args()
    run(args.input, args.output)
